version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:13.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    env_file:
      - .env
    volumes:
      - ./data/images:/home/images
  web_admin:
    container_name: web_admin
    build:
      context: .
      dockerfile: ./docker/admin.DockerFile
    volumes:
      - ./data/images:/home/images
    env_file:
      - .env