"""'add_admin'

Revision ID: a66e93578545
Revises: ad539ec9aa12
Create Date: 2022-11-22 13:36:29.932862

"""
# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a66e93578545"
down_revision = "ad539ec9aa12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=80), nullable=True, comment="логин"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "password_hashed",
            sa.String(),
            nullable=False,
            comment="Зашифрованный пароль",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.drop_constraint("image_task_id_fkey", "image", type_="foreignkey")
    op.create_foreign_key(
        "image_task_id_fkey", "image", "task", ["task_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "labeled_image_tg_login_fkey", "labeled_image", type_="foreignkey"
    )
    op.drop_constraint(
        "labeled_image_image_id_fkey", "labeled_image", type_="foreignkey"
    )
    op.drop_constraint(
        "labeled_image_label_id_fkey", "labeled_image", type_="foreignkey"
    )
    op.create_foreign_key(
        "labeled_image_tg_login_fkey",
        "labeled_image",
        "tg_user",
        ["tg_login"],
        ["login"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "labeled_image_image_id_fkey",
        "labeled_image",
        "image",
        ["image_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "labeled_image_label_id_fkey",
        "labeled_image",
        "label_class",
        ["label_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "task_label_class_label_class_id_fkey", "task_label_class", type_="foreignkey"
    )
    op.drop_constraint(
        "task_label_class_task_id_fkey", "task_label_class", type_="foreignkey"
    )
    op.create_foreign_key(
        "task_label_class_label_class_id_fkey",
        "task_label_class",
        "label_class",
        ["label_class_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "task_label_class_task_id_fkey",
        "task_label_class",
        "task",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("task_tg_user_tg_login_fkey", "task_tg_user", type_="foreignkey")
    op.drop_constraint("task_tg_user_task_id_fkey", "task_tg_user", type_="foreignkey")
    op.create_foreign_key(
        "task_tg_user_tg_login_fkey",
        "task_tg_user",
        "tg_user",
        ["tg_login"],
        ["login"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "task_tg_user_task_id_fkey",
        "task_tg_user",
        "task",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_tg_user_task_id_fkey", "task_tg_user", type_="foreignkey")
    op.drop_constraint("task_tg_user_tg_login_fkey", "task_tg_user", type_="foreignkey")
    op.create_foreign_key(
        "task_tg_user_task_id_fkey", "task_tg_user", "task", ["task_id"], ["id"]
    )
    op.create_foreign_key(
        "task_tg_user_tg_login_fkey", "task_tg_user", "tg_user", ["tg_login"], ["login"]
    )
    op.drop_constraint(
        "task_label_class_task_id_fkey", "task_label_class", type_="foreignkey"
    )
    op.drop_constraint(
        "task_label_class_label_class_id_fkey", "task_label_class", type_="foreignkey"
    )
    op.create_foreign_key(
        "task_label_class_task_id_fkey", "task_label_class", "task", ["task_id"], ["id"]
    )
    op.create_foreign_key(
        "task_label_class_label_class_id_fkey",
        "task_label_class",
        "label_class",
        ["label_class_id"],
        ["id"],
    )
    op.drop_constraint(
        "labeled_image_label_id_fkey", "labeled_image", type_="foreignkey"
    )
    op.drop_constraint(
        "labeled_image_image_id_fkey", "labeled_image", type_="foreignkey"
    )
    op.drop_constraint(
        "labeled_image_tg_login_fkey", "labeled_image", type_="foreignkey"
    )
    op.create_foreign_key(
        "labeled_image_label_id_fkey",
        "labeled_image",
        "label_class",
        ["label_id"],
        ["id"],
    )
    op.create_foreign_key(
        "labeled_image_image_id_fkey", "labeled_image", "image", ["image_id"], ["id"]
    )
    op.create_foreign_key(
        "labeled_image_tg_login_fkey",
        "labeled_image",
        "tg_user",
        ["tg_login"],
        ["login"],
    )
    op.drop_constraint("image_task_id_fkey", "image", type_="foreignkey")
    op.create_foreign_key("image_task_id_fkey", "image", "task", ["task_id"], ["id"])
    op.drop_table("web_user")
    # ### end Alembic commands ###
