"""'added_task_status'

Revision ID: ad539ec9aa12
Revises: 5177b4efa327
Create Date: 2022-11-21 14:56:02.771575

"""
# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad539ec9aa12"
down_revision = "5177b4efa327"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_tg_user", sa.Column("status", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_tg_user", "status")
    # ### end Alembic commands ###
