"""'delete_task_name'

Revision ID: b7ea2c5ad7a1
Revises: a66e93578545
Create Date: 2022-11-22 19:09:52.982193

"""
# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7ea2c5ad7a1"
down_revision = "a66e93578545"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Название задачи",
        ),
    )
    # ### end Alembic commands ###
